// <auto-generated />
using System;
using APPR_AZURE_CONNECT.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APPR_AZURE_CONNECT.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230909185228_TablesMont&Disaster")]
    partial class TablesMontDisaster
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APPR_AZURE_CONNECT.Models.DisasterEntity", b =>
                {
                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequiredAidTypes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StartDate");

                    b.ToTable("Disaster");
                });

            modelBuilder.Entity("APPR_AZURE_CONNECT.Models.LeadEntity1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DonateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DonateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Item")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Donation");
                });

            modelBuilder.Entity("APPR_AZURE_CONNECT.Models.MonetDonateEntity", b =>
                {
                    b.Property<string>("DonatorsName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("DonationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("DonatorsName");

                    b.ToTable("MonetDonation");
                });
#pragma warning restore 612, 618
        }
    }
}
